# 梯度下降

本文件用于实现批梯度下降与随机梯度下降相关的内容

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### 批梯度下降

In [3]:
R1 = np.eye(3, dtype=float) - 0.04 * np.array([[25, -15, -20], 
                                               [-15, 9, 12], 
                                               [-20, 12, 16]])
A = np.array([[0, -20, -14],
             [3, 27, -4],
             [4, 11, -2]])

print(R1 @ A)

[[ 5.0000000e+00  2.5000000e+01 -4.0000000e+00]
 [ 0.0000000e+00  4.4408921e-16 -1.0000000e+01]
 [ 0.0000000e+00 -2.5000000e+01 -1.0000000e+01]]


### 随机梯度下降